import { useState } from "react";
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import "./App.css";
import Cards from "./components/Cards";

function App() {
  const [count, setCount] = useState(0);

  return (
   <div>
    <div className="fixed inset-0 -z-10 h-full w-full items-center px-5 py-24 [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]"></div>
    <div>
        <h2 className="text-white mt-28 font-extrabold text-4xl">
          Your Favourite Genre Generated by BookAI
        </h2>
        <p className="text-white mt-8 font-bold">
          Explore some of the captivating books created using our AI technology.
        </p>

        <div className="flex flex-wrap  justify-between mt-16">
          <Cards
            className="justify-center space-x-32 space-y-32"
            name="Action"
            content=" Feel the Rush: Experience Thrilling Action"
          />
          <Cards
            className="justify-center space-x-32 space-y-32 "
            name="Drama"
            content="Unravel Emotions: Discover Compelling Drama "
          />
          <Cards
            className="justify-center space-x-32 space-y-32 "
            name="Scifi"
            content="Explore New Worlds: Dive into Science Fiction"
          />
          <Cards
            className="justify-center space-x-32 space-y-32"
            name="Comedy"
            content="Laugh Out Loud: Explore the World of Comedy Books"
          />
        </div>
      </div>
   </div>
  );
}

export default App;
